In [22]:
import pandas as pd
import re
import nltk

In [45]:
# Download necessary NLTK corpora and tokenizer models for text processing
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [3]:
# Load the Coachella tweets dataset with proper encoding
df = pd.read_csv("Coachella-2015-2-DFE.csv", encoding='latin-1')
df

,coachella_sentiment,coachella_yn,name,retweet_count,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
0,positive,yes,kokombil,0,#Coachella2015 tickets selling out in less tha...,"[0.0, 0.0]",1/7/15 15:02,5.529630e+17,NaN,Quito
1,positive,yes,MisssTaraaa10,2,RT @sudsybuddy: WAIT THIS IS ABSOLUTE FIRE _ÙÓ...,NaN,1/7/15 15:02,5.529630e+17,united states,NaN
2,positive,yes,NMcCracken805,0,#Coachella2015 #VIP passes secured! See you th...,NaN,1/7/15 15:01,5.529630e+17,"Costa Mesa, CA",NaN
3,positive,yes,wxpnfm,1,PhillyÛªs @warondrugsjams will play #Coachell...,NaN,1/7/15 15:01,5.529630e+17,"Philadelphia, PA and Worldwide",Quito
4,positive,yes,Caesears,0,If briana and her mom out to #Coachella2015 i...,NaN,1/7/15 15:00,5.529630e+17,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3841,cant tell,yes,MissXOverdose,0,Excuse me while I go cry now. _Ù÷¢ #Coachella2...,NaN,1/6/15 10:32,5.525330e+17,atx,Pacific Time (US & Canada)
3842,cant tell,yes,NedRaggett,1,RT @touchofallright: Ride and Steely Dan. It w...,NaN,1/6/15 10:28,5.525320e+17,"Costa Mesa, CA",Pacific Time (US & Canada)
3843,cant tell,yes,nicolejackieee,0,I've been callin that since day one #Coachella...,NaN,1/6/15 10:26,5.525320e+17,NaN,NaN
3844,cant tell,yes,NiqueWobbitz,2,Is this for real?!?! #Coachella2015 http://t.c...,NaN,1/6/15 10:21,5.525300e+17,Huntington Beach X Long Beach,Pacific Time (US & Canada)
3845,cant tell,yes,LindsayRuben,1,RT @Jen_Baz: C'monnnnnn lineup! #coachella2015...,NaN,1/6/15 6:44,5.524760e+17,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3846 entries, 0 to 3845
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   coachella_sentiment  3846 non-null   object
 1   coachella_yn         3846 non-null   object
 2   name                 3846 non-null   object
 3   retweet_count        3846 non-null   int64
 4   text                 3846 non-null   object
 5   tweet_coord          242 non-null    object
 6   tweet_created        3846 non-null   object
 7   tweet_id             3846 non-null   float64
 8   tweet_location       2676 non-null   object
 9   user_timezone        2863 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 300.6+ KB

**Find** all the hashtags in the tweets, such as #coachella, #beychella, etc. Extract them and save them in a separate column named "hashtags".

In [10]:
df['hashtags'] = df['text'].apply(lambda x: re.findall(r'#\w+', x))
df['hashtags']

0                     [#Coachella2015]
1                     [#Coachella2015]
2               [#Coachella2015, #VIP]
3       [#Coachella2015, #GovBall2015]
4                     [#Coachella2015]
                     ...
3841                  [#Coachella2015]
3842                  [#Coachella2015]
3843                  [#Coachella2015]
3844                  [#Coachella2015]
3845      [#coachella2015, #Impatient]
Name: hashtags, Length: 3846, dtype: object

Find all the emails in the tweets, such as example@gmail.com, user@yahoo.com, etc. Extract them and save them in a separate column named "emails".**bold text**

In [13]:
df['emails'] = df['text'].apply(lambda x: re.findall(r'[\w.]+@\w+\.[A-Za-z]{2,}', x))
df['emails']

0       []
1       []
2       []
3       []
4       []
        ..
3841    []
3842    []
3843    []
3844    []
3845    []
Name: emails, Length: 3846, dtype: object

**Write the following functions to remove unwanted elements from the tweets and apply them to the new tweets text column:**

**remove_usernames:** *This function should remove any usernames that start with @, such as @coachella, @beyonce, etc.*

In [33]:
def remove_usernames(text):
  return re.sub(r'@\w+', '', str(text))

**remove_links:** *This function should remove any links that start with http or https, such as https://www.coachella.com/, http://bit.ly/2GdOZLz, etc.*

In [34]:
def remove_links(text):
  return re.sub(r'\b(?:https|http)\S+', '', str(text))

**remove_non_ascii_symbols:** *This function should remove any symbols that are not part of the ASCII character set, such as emojis, accented letters, etc.*

In [35]:
def remove_non_ascii_symbols(text):
  return re.sub(r'[^\x00-\x7F]', '', text)

**to_lower:** *This function should convert all the letters in the tweet text to lower case, such as COACHELLA to coachella, Beyoncé to beyoncé, etc.*

In [36]:
def to_lower(text):
  return text.lower()

**remove_stop_words:** *This function should remove any common words that do not add much meaning to the tweet text, such as the, a, an, and, etc.*

In [44]:
def remove_stop_words(text):
  token = nltk.word_tokenize(text)
  stopwords = nltk.corpus.stopwords.words("english")
  result = [t for t in token if t.lower() not in stopwords]
  return " ".join(result)

**remove_digits:** *This function should remove any numbers in the tweet text, such as 2018, 10, 100, etc.*

In [39]:
def remove_digits(text):
  return re.sub(r'\d+', '', text)

**remove_special_characters:** This function should remove any punctuation marks or other special characters in the tweet text, such as . , ! ? # $ % & * ( ) + = - _ [ ] { } ; : ' " / \ | < > ` ~, etc. *italicized text*

In [46]:
def remove_special_characters(text):
  return re.sub(r'[^a-zA-Z0-9\s]', '', text)

In [47]:
df["cleaned_text"] = df["text"]

df["cleaned_text"] = df["cleaned_text"].apply(remove_usernames)
df["cleaned_text"] = df["cleaned_text"].apply(remove_links)
df["cleaned_text"] = df["cleaned_text"].apply(remove_non_ascii_symbols)
df["cleaned_text"] = df["cleaned_text"].apply(to_lower)
df["cleaned_text"] = df["cleaned_text"].apply(remove_stop_words)
df["cleaned_text"] = df["cleaned_text"].apply(remove_digits)
df["cleaned_text"] = df["cleaned_text"].apply(remove_special_characters)
df["cleaned_text"]

0                coachella tickets selling less  minutes
1                      rt  wait absolute fire   coachella
2          coachella  vip passes secured  see bitchesssss
3       phillys play  coachella  amp   govball  watch ...
4                            briana mom  coachella im
                              ...
3841                           excuse go cry    coachella
3842    rt  ride steely dan  would better supergroup  ...
3843                   ve callin since day one  coachella
3844                                  real      coachella
3845          rt  cmonnnnnn lineup   coachella  impatient
Name: cleaned_text, Length: 3846, dtype: object

In [48]:
df["cleaned_text"][0]

' coachella tickets selling less  minutes '

In [49]:
df['text'][0]

'#Coachella2015 tickets selling out in less than 40 minutes _Ù_¦_Ù___Ù___Ù÷\x9d_ÙÎµ_ÙÎµ_Ù___Ù_¦ http://t.co/SmoXyteIMJ'